#! /bin/bash

GITREV=`git rev-parse --short HEAD`
[[ $# -gt 1 ]] && GITREV=$1

echo $GITREV

TARGET_DIR=$HOME/rpmbuild/SOURCES
mkdir -p $TARGET_DIR
git archive ${GITREV} --prefix=hawkey/ | xz > $TARGET_DIR/hawkey-${GITREV}.tar.xz
