#! /bin/bash

GITREV=`git rev-parse HEAD`
[[ $# -gt 1 ]] && GITREV=$1

echo $GITREV

TARGET_DIR=$HOME/rpmbuild/SOURCES
mkdir -p $TARGET_DIR
git archive ${GITREV} --prefix=hawkey-${GITREV}/ -o $TARGET_DIR/hawkey-${GITREV}.tar.gz
