#ifndef LIBDNF_TESTMACROS_HPP
#define LIBDNF_TESTMACROS_HPP

#define UNITTEST_DIR "/tmp/libdnf.XXXXXX"
#define YUM_DIR_SUFFIX "yum/repodata/"
#define YUM_REPO_NAME "nevermac"
#define TEST_FIXED_ARCH "x86_64"
#define TEST_EXPECT_SYSTEM_PKGS 13
#define TEST_EXPECT_SYSTEM_NSOLVABLES TEST_EXPECT_SYSTEM_PKGS
#define TEST_EXPECT_MAIN_NSOLVABLES 14
#define TEST_EXPECT_UPDATES_NSOLVABLES 10
#define TEST_EXPECT_YUM_NSOLVABLES 2

#endif //LIBDNF_TESTMACROS_HPP
