#! /bin/bash

THISDIR=$(readlink -f $(dirname $0))
cd $THISDIR
git rm -rf repodata/ drpms/
createrepo --deltas --oldpackagedirs=../yum_oldrpms/ --no-database --baseurl blah .
git add repodata/ drpms/
